CREATE TABLE PROJECTS (
	PNO		INTEGER			NOT NULL	COMMENT '프로젝트일련번호',
	PNAME		VARCHAR(255)	NOT NULL	COMMENT '프로젝트명',
	CONTENT	TEXT				NOT NULL COMMENT '설명',
	STA_DATE	DATETIME			NOT NULL	COMMENT '시작일',
	END_DATE DATETIME			NOT NULL	COMMENT '종료일',
	STATE		INTEGER			NOT NULL COMMENT '상태',
	CRE_DATE	DATETIME			NOT NULL COMMENT '생성일',
	TAGS		VARCHAR(255)	NULL		COMMENT '태그'
	) COMMENT '프로젝트';