CREATE TABLE PRJ_MEMBS(
	PNO INTEGER NOT NULL COMMENT '프로젝트일련번호',
	MNO INTEGER NOT NULL COMMENT '회원일련번호',
	GRADE	INTEGER NOT NULL COMMENT '등급',
	STATE INTEGER NOT NULL COMMENT '상태',
	MOD_DATE DATETIME NOT NULL COMMENT '상태변경일'
	) COMMENT '프로젝트멤버';