-- CREATE TABLE
CREATE TABLE MEMBERS (
	MNO		INTEGER			NOT NULL	COMMENT	'회원일련번호',
	EMAIL		VARCHAR(40)		NOT NULL COMMENT	'이메일',
	PWD		VARCHAR(100)	NOT NULL	COMMENT	'이름',
	MNAME		VARCHAR(50)		NOT NULL	COMMENT	'가입일',
	CRE_DATE	DATETIME			NOT NULL COMMENT	'가입일',
	MOD_DATE	DATETIME			NOT NULL COMMENT	'마지막암호변경일'
) COMMENT '회원기본정보';